---
title: "Data Import"
output: github_document
---

This document will show how to tidy data.

```{r setup, echo=FALSE, message=FALSE}
library(tidyverse)
```

```{r}
pulse_df=
  read_sas("data/public_pulse_data.sas7bdat") |>
  janitor::clean_names()
```

```{r}
pulse_tidy_df =
  pulse_df |>
  pivot_longer(
    cols= bdi_score_bl:bdi_score_12m,
    names_to= "visit",
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
  ) |>
  mutate(
    visit = replace(visit, visit == "bl", "00m") 
  )|>
  relocate(id, visit)
```


He would do all that like this in one block:

```{r}
pulse_df=
  read_sas("data/public_pulse_data.sas7bdat") |>
  janitor::clean_names() |>
  # new part:
  pivot_longer(
    cols= bdi_score_bl:bdi_score_12m,
    names_to= "visit",
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
  ) |>
  # new part end
  mutate(
    visit = replace(visit, visit == "bl", "00m") 
  )|>
  relocate(id, visit)
```

Do one more example:

```{r}
litters_df=
  read_csv("data/FAS_litters.csv", na= c("NA", ".", "")) |>
  janitor::clean_names()
```

Gestational 0 and gestational 18, we want it to be better. we want a var gestation with 0 and 18 and then weight that says the number. 

```{r}
litters_df=
  read_csv("data/FAS_litters.csv", na= c("NA", ".", "")) |>
  janitor::clean_names() |>
  pivot_longer(
    cols= gd0_weight:gd18_weight,
    names_to = "gd_time", 
    values_to = "weight"
  ) |> 
  mutate(
    gd_time = case_match(
      gd_time,
      "gd0_weight"  ~ 0,
      "gd18_weight" ~ 18
    ))

#case match requires you to list all options and what you want it wo 
# case win also exists.
```



